### ISSUE TITLE
Port waypoint altitude controls to logistics order screen

### ISSUE THREAD

**Issue by hoylemd** [Quantx/CC2-UI-Enhancer#14]
If you're working with ammunition, increments of 100 still take *forever* to order, so it'd be nice if we had more increment options.

**Comment by Lugghawk** [comment]
This feels pretty tough given the difference in magnitude that we need to handle. I tried this, and while it's functional it doesn't really feel that great. 

![image](https://user-images.githubusercontent.com/508278/130330007-036119c7-27ab-464f-8a7a-100392b3ff99.png)

I was trying to figure out if there was a way to detect if shift or ctrl are being held down, and we could change the values when they are. Haven't found anything yet, but that might be a nice option for it.

**Comment by ambispess** [comment]
second pic's solution seems pretty good to me!

**Comment by hoylemd** [comment]
Yeah that looks good imo. Pretty much just what I had in mind!
