### ISSUE TITLE
PTR and RZR show "PARK" instead of "STBY"

### ISSUE THREAD

**Issue by LazyBoot** [Quantx/CC2-UI-Enhancer#17]
PTR and RZR show "PARK" instead of "STBY" before they switch to "LNCH" on the air traffic display
Also they don't show "LNCH" until they are on the elevator, unlike the MNT that will switch to LNCH while being moved by the crane as well. (Instead showing "PARK" until on the elevator)

**Comment by Quantx** [comment]
Fixed in 45dd235
