### ISSUE TITLE
Show Type of Ammo for Weapon

### ISSUE THREAD

**Issue by bframke** [Quantx/CC2-UI-Enhancer#4]
Would it be possible to show the Type of Ammo that is used for Carrier Weapons?

**Comment by Quantx** [comment]
I suppose I could add a tooltip for it. There's not really much space left on the carrier weapons screen for that info to be anywhere else.

**Comment by bframke** [comment]
Okay, you could also use like a short version? Like just 160mm for example

**Comment by Quantx** [comment]
I don't think I'll be adding this. This should just be common knowledge.

For those that don't know:

AA Launcher uses AA Missiles
CWIS uses 20mm bullets
Cruise Missile Launcher uses Cruise Missiles
Carrier Gun uses 160mm shells
