### ISSUE TITLE
Mule is displayed in the wrong place

### ISSUE THREAD

**Issue by 5trubel** [Quantx/CC2-UI-Enhancer#42]
Hello all!
The mule is displayed as "air unit" and not as "ground unit". 
When you select it, it spawns in the hangar and the game crashes when it is launched.
![image](https://user-images.githubusercontent.com/45943082/193306414-ef035ce0-ff7f-4f46-bdfb-cabc0d6d1c07.png)

**Comment by jr-uk** [comment]
Should be addressed with [this PR](https://github.com/Quantx/CC2-UI-Enhancer/pull/40)

**Comment by 5trubel** [comment]
Is fixed in the newest Version.
Thanks for fixing!
