### ISSUE TITLE
UI enhancer compatibility issues with latest 17th March version of CC2

### ISSUE THREAD

**Issue by jasonculligan** [Quantx/CC2-UI-Enhancer#45]
Since the new release from CC2 on 17th March, the UI Enhancer is causing issues.

1. The new gimbal guns on aircraft are showing as UNKNOWN equipment when UI Enhancer mod is enabled.
2. The new zoom and centre to mouse feature in the new release is overridden by the UI Enhancer and so doesn't work.

**Comment by Quantx** [comment]
The mod has been updated to support the latest patch
