### ISSUE TITLE
Holomap zoom does not work with 17 March 1.5.1 update

### ISSUE THREAD

**Issue by Floydii** [Quantx/CC2-UI-Enhancer#46]
The main holomap  zooms do not work in this latest release (17 March 23). the tooltip for zoom says 'p/esc', but pressing either of those just exits the map.

I note that scroll zooming works fine on other workstations.

**Comment by Quantx** [comment]
This has been fixed in ad5d141a14e9b06d6d35dfa37035c01fafc3106b
