### ISSUE TITLE
[Request] Show waypoints of own vehicle in tab map

### ISSUE THREAD

**Issue by TelluriumCrystal** [Quantx/CC2-UI-Enhancer#5]
Since the vehicle HUD rendering is exposed do you think it would be possible to render the waypoints for the current vehicle in the tab map? This would be particularly useful for taking manual control of stuck vehicles and knowing where you originally wanted them to go without needing to back out to the vehicle control screen.

**Comment by Quantx** [comment]
I've looked into this and at it is impossible at this time. The engine callback which is needed to get the waypoints for a vehicle `update_get_map_vehicle_by_id()` is not accessible from within the vehicle hud's lua file.

**Comment by TelluriumCrystal** [comment]
That's unfortunate. Regardless, thanks for taking a look!
